polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
  path("",views.IndexView.as_view(), name="index"),
  path("details/<int:pk>", views.DetailView.as_view(), name="details"),
  path("add", views.QuestionView.as_view(), name="add"),
]

sondage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
  question_text = models.CharField(max_length=255)
  pub_date = models.DateTimeField("date publication")
  
  def __str__(self):
    return self.question_text

class Choice(models.Model):
  choice_text = models.CharField(max_length=255)
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  votes = models.IntegerField(default=0)
  
  def __str__(self):
    return self.choice_text


# P@ssword

polls/views.py
from django.shortcuts import render

from django.http import (HttpResponse, Http404)
from .models import Question
from django.views import generic

from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView

from django.utils import timezone


class IndexView(generic.ListView):
  template_name = 'index.html'
  context_object_name = 'questions'
  
  def get_queryset(self):
    return Question.objects.all()
  
  

# def index(request):
#   questions = Question.objects.all()
#   context = {
#     'questions':questions
#   }
#   return render(request,"index.html",context)

class DetailView(generic.DetailView):
  model = Question
  template_name='details.html'
  

# def details(request,question_id):
  
#   # try:
#   #   question = Question.objects.get(id=question_id)
#   # except:
#   #   raise Http404("Cette question n'existe pas")
  
#   question = get_object_or_404(Question, pk=question_id)
#   context = {
#     "question": question
#   }
  
  # return render(request,"details.html",context)

# Create your views here.

# demande : GET, POST, PUT, DELETE


def getQuestion(request):
  questions = Question.objects.all()
  return render(request,'index.html',{
    "questions":questions
    })
  
  
def create_question(request):
  question = Question.objects.create(
    question_text=request.GET.get('question'),
    pub_date=timezone.now())
  questions = Question.objects.all()
  return render(request,'index.html',{"questions":questions})


# def addQuestion(request):   
#   if request.POST:
#     question = Question.objects.create(
#     question_text=request.POST.get('question'),
#     pub_date=timezone.now())
#     return render(request,'details.html',{"question":question})
#   else:
#      return render(request,'addQuestion.html')
  
  
class QuestionView(TemplateView):
  def get(self,request):
    return render(request,'addQuestion.html')
  
  def post( self, request):
    question = Question.objects.create(
    question_text=request.POST.get('question'),
    pub_date=timezone.now())
    return render(request,'details.html',{"question":question})
    
  

polls/templates/addQuestion.html
{% extends 'layout.html' %}


{% block title %}
Ajout de question
{% endblock title %}

{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label for="text_question">Question</label>
        <input type="text" class="form-control" name="question" placeholder="Question">
      </div>
      <button type="submit" class="btn btn-primary btn-sm">Ajouter</button>
    </div>
  </div>
</form>

{% endblock content %}

polls/templates/details.html
{% extends 'layout.html' %}

{% block title %}{{ question.question_text }}{% endblock title %}

{% block content %}
<div class="content">
  <h1>Detail: <small>{{ question.question_text }}</small></h1>

  <div class="row">
    <div class="col-md-12">
      <a href="{% url 'polls:index' %}" class="btn btn-secondary btn-sm">Retour</a>
    </div>
  </div>

</div>
{% endblock content %}

polls/templates/index.html
{% extends 'layout.html' %}


{% block title %}Acceuil{% endblock title %}

{% block content %}

<div class="content">
  <div class="row">
    <div class="col-md-12">
      <a href="{% url 'polls:add' %}" class="btn btn-primary btn-sm">Ajouter</a>
    </div>
  </div>
  <ul>

    {% for question in questions %}
    <li>
      <a href="{% url 'polls:details' question.id %}">
        {{ question.question_text }}
      </a>
    </li>
    {% endfor %}

  </ul>
</div>

{% endblock content %}

polls/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=poll, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <title>
    Poll | {% block title %} {% endblock title %}
  </title>
</head>

<body>

  <div class="container">
    {% block content %}
    valeur par defaut
    {% endblock %}
  </div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</html>